last_update = 1678005289112
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.ply.gg"]
control_address = "control.ply.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "79512b7345ec9f11f14261cad5b15d34dac3d1e386061f5d37b4b960405e43ec"

[[mappings]]
name = "mc"
proto = "tcp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 64481
local_port = 25565
